services:

  readsb:
    container_name: readsb
    image: ghcr.io/tyz/readsb:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - ./data:/data:rw
    env:
      ENABLE_BIAS_T: false
      HEYWHATSTHAT_ID: "ABC12DEF"
      HEYWHATSTHAT_ID_ALTS: "5000,15000,30000"
    command: >
      --device-type rtlsdr
      --ppm 3
      --gain auto-verbose
      --lat 51.889997
      --lon 1.476164
      --write-json /data
      --write-json-every 1
      --write-json-globe-index
      --write-globe-history /data/globe_history
      --write-receiver-id-json
      --json-location-accuracy 2
      --db-file /usr/local/share/tar1090/aircraft.csv.gz
      --heatmap 30
      --net
      --net-api-port 30154
      --tar1090-use-api

  tar1090:
    container_name: tar1090
    image: ghcr.io/tyz/tar1090:latest
    restart: unless-stopped
    volumes:
      - ./data:/usr/share/nginx/html/data:ro
